### ISSUE TITLE
数据放回后想进行权限判断，要怎么取到里边实际的数据啊

### ISSUE THREAD

**Issue by DXDZY** [umijs/umi-request#10]
request.interceptors.response.use((res, options) => {
//返回的res并不是实际后端返回的数据，要怎么拿到实际的数据啊
  if (
    res.ret === -1 &&
    (res.code === 'FALL' ||
      res.code === 'SSO_FALL' ||
      res.code === 'NO_PERMISSION' ||
      res.code === 'ILLEGAL_REQUEST')
  ) {
    router.push('/403');
  } else if (res.ret === -1 && res.code === 'NO_LOGIN') {
    goLogin();
  }
  return res;
});

**Comment by clock157** [comment]
interceptors 中返回的是 Response 对象，获取数据需要

```javascript
// res 对象只能被解析一次，需要克隆一份。
const clone = res.clone();
// 解析 response
const data = clone.json();
if(data.code) {
   // do something
}
return res;
```

**Comment by DXDZY** [comment]
@clock157 非常感谢您，困扰了一下午，感谢🙏
