### ISSUE TITLE
如何增加自定义参数而不报错

### ISSUE THREAD

**Issue by miaozilong** [umijs/umi-request#100]
![image](https://user-images.githubusercontent.com/3994941/71904011-46c40000-31a0-11ea-9d51-997f57467449.png)
这段代码是可以执行的.
但是eslint会报错.
![image](https://user-images.githubusercontent.com/3994941/71904082-6c510980-31a0-11ea-801c-7a33eb3d3fec.png)

我想加个log参数,然后在拦截器中进行处理,
代码都写完了  可以用  但是不想看到这个报错.

**Comment by miaozilong** [comment]
这个库还有人维护吗?
都回家过年啦?

**Comment by chenjsh36** [comment]
年底活多，不好意思~。这个是类型推导的问题，一般不建议往 request 的 options 里加入自定义参数，避免未来和 umi-request 新增参数重名的问题，建议将 log 参数放到 data、params 中避免检测的问题

**Comment by wenlittleoil** [comment]
> 年底活多，不好意思~。这个是类型推导的问题，一般不建议往 request 的 options 里加入自定义参数，避免未来和 umi-request 新增参数重名的问题，建议将 log 参数放到 data、params 中避免检测的问题

在options里加入自定义参数是一个常见需求场景。例如在当接口返回的响应体里的err_code不为0时，统一弹出错误提示err_msg，但是这种行为可通过调用request方法时才传入选项控制。

**Comment by wenlittleoil** [comment]
> > 年底活多，不好意思~。这个是类型推导的问题，一般不建议往 request 的 options 里加入自定义参数，避免未来和 umi-request 新增参数重名的问题，建议将 log 参数放到 data、params 中避免检测的问题
> 
> 在options里加入自定义参数是一个常见需求场景。例如在当接口返回的响应体里的err_code不为0时，统一弹出错误提示err_msg，�但是这种行为可通过调用request方法时才传入选项参数控制。
