### ISSUE TITLE
如何解决CORS问题？

### ISSUE THREAD

**Issue by yhcnux** [umijs/umi-request#105]
用umi-serve在8001端口上做mock server，然后服务器是tomcat起在8000上的，所有的api调用都会提示CORS policy的问题，在网上搜了一些解决方案，然后在antd pro的util/request.ts上加上如下内容

`const request = extend({
  prefix: 'http://localhost:8001', 
  errorHandler, // 默认错误处理
  credentials: 'include', // 默认请求是否带上cookie
  headers: {
    'Access-Control-Allow-Credentials': true,
    'Access-Control-Allow-Origin': 'http://localhost:8001',
    'Access-Control-Allow-Headers': 'x-requested-with'
  },
});`

还是不行，不知道如何解决，求帮助，谢谢

**Comment by MeXunco** [comment]
仔细参考 https://www.ruanyifeng.com/blog/2016/04/cors.html，
> 非简单请求的CORS请求，会在正式通信之前，增加一次HTTP查询请求，称为"预检"请求（preflight）

是服务器端需要对其进行处理(关键词自己搜索 `java` 跨域)

**Comment by fanyinghao** [comment]
我也提个问题：

服务器nginx 上配置了返回header带上'Access-Control-Allow-Origin':*，同时支持options请求。
在旧版本的antd里，是会先请求options，然后支持了跨域。

目前antd4.0用了新版的umi request后，也不知道什么原因，出现了跨域问题（没再请求options），浏览器都不发送正常请求了直接ban掉。

**Comment by chenjsh36** [comment]
> 我也提个问题：
> 
> 服务器nginx 上配置了返回header带上'Access-Control-Allow-Origin':*，同时支持options请求。
> 在旧版本的antd里，是会先请求options，然后支持了跨域。
> 
> 目前antd4.0用了新版的umi request后，也不知道什么原因，出现了跨域问题（没再请求options），浏览器都不发送正常请求了直接ban掉。
> 
> 就是不知道是否有配置开关这个preflight.

antd 4.0 和 umi-request 没有强绑定的，跨域问题一般是浏览器同源策略限制，可以排查下前后端配置是否正常，或提供 DEMO 和截图信息，我们帮忙看下。

**Comment by ystarlongzi** [comment]
@fanyinghao 

可以看下 2 楼贴的阮一峰的那篇文章，确定下自己是否添加了自定义头

我之前也有碰到过类似的问题，就是因为添加了自定义头，导致「预检」失败

**Comment by fanyinghao** [comment]
> > 我也提个问题：
> 
> > 
> 
> > 服务器nginx 上配置了返回header带上'Access-Control-Allow-Origin':*，同时支持options请求。
> 
> > 在旧版本的antd里，是会先请求options，然后支持了跨域。
> 
> > 
> 
> > 目前antd4.0用了新版的umi request后，也不知道什么原因，出现了跨域问题（没再请求options），浏览器都不发送正常请求了直接ban掉。
> 
> > 
> 
> > 就是不知道是否有配置开关这个preflight.
> 
> 
> 
> antd 4.0 和 umi-request 没有强绑定的，跨域问题一般是浏览器同源策略限制，可以排查下前后端配置是否正常，或提供 DEMO 和截图信息，我们帮忙看下。

经过检查，是request方法里加入了`credentials: include` 而服务端没支持。多谢解释。
