### ISSUE TITLE
通过umi-request发起Get 跨域请求，如果url 是域名那么Header里面会丢Origin

### ISSUE THREAD

**Issue by BarronLin** [umijs/umi-request#106]
1.在http://localhost:8000/ 页面同时发起两个到服务器的跨域请求：

```
  request('http://apigw-gateway.v190808.163skiff.com/org/verify/base64image')
  request('http://59.111.58.175:8870/verify/base64image');
```

发起通过域名apigw-gateway.v190808.163skiff.com 访问的请求头没有Origin ，
但是直接通过IP 访问的请求有这个Origin

**Comment by chenjsh36** [comment]
umi-request 不会在header 中添加 origin 字段，这个应该属于浏览器的默认行为
