### ISSUE TITLE
通过umi-request发起Get 请求，如果在body里传参

### ISSUE THREAD

**Issue by IsaacHo** [umijs/umi-request#109]
如题。支持吗？

**Comment by chenjsh36** [comment]
不支持，umi-request 提供 params、data 两个参数，params 参数会拼装到 url 后，data 会处理到赋值给 body，建议通过 params 来传所需要的参数；

GET 请求本身不发送 body，所以即使传了值也无法发送给后端呢

**Comment by ystarlongzi** [comment]
get 请求，不支持 body 发送参数，和库无关

**Comment by GuyCheung** [comment]
需要这一个功能。。

**Comment by keke122765** [comment]
get请求没有body，别想了

**Comment by gaozhidf** [comment]
需要这个功能+1

**Comment by mjkohoh** [comment]
需要这个功能+1
