### ISSUE TITLE
建议增加一个kv参数用于一些自定义的场景

### ISSUE THREAD

**Issue by xiexingen** [umijs/umi-request#112]
比如： 
request.post('',{successTip:true})
这里添加了一个successTip为true，那么自己在拦截器里面可以获取到当前请求的配置信息；可以根据一些配置做一些自定义的操作 必填弹保存成功的消息

**Comment by wanghanzhen** [comment]
附议

**Comment by chenjsh36** [comment]
下个版本将更新 Types，方便使用者自行传入自定义参数。

**Comment by hanxinimm** [comment]
静静的等待下个版本增加自定义参数

**Comment by hanxinimm** [comment]
@chenjsh36  几个月过去了，这个库还更不更新了，等着加功能呢

**Comment by xiexingen** [comment]
表示等不及，已经用axios代替了

**Comment by chenjsh36** [comment]
不好意思，types 已更新
