### ISSUE TITLE
extend 中 如何带参数

### ISSUE THREAD

**Issue by basung** [umijs/umi-request#116]
const request = extend({
	errorHandler,
	// 默认错误处理
	credentials: 'include', // 默认请求是否带上cookie
	headers: {
		'Authorization': localStorage.getItem('Authorization')
	}
});
headers中的Authorization一直不变，只有刷新页面才会变化。

**Comment by chenjsh36** [comment]
这样配置是没错的，没有变化是因为 extend 只在调用时执行，所以 Authorization 只在 extend 被调用时初始化，并不会随着每次请求不断调用 extend（这个会带来性能损耗）。

如果你希望每次请求时都动态获取 localStorage 的 Authorization ，可以通过中间件来前置处理，或者在每次请求中自行获取传给 header 。

**Comment by coy9** [comment]
我使用了拦截器 
request.interceptors.request.use((url, options: any) => {
  options.headers.Authorization = `JWT ${localStorage.getItem('zy-token')}`
  return (
    {
      // url: `${url}&interceptors=yes`,
      options: { ...options, interceptors: true },
    }
  );
});
