### ISSUE TITLE
服务端传了长整型id，到前端的时候精度丢失，请问有没有像axios的transformResponse处理方式

### ISSUE THREAD

**Issue by hopechans** [umijs/umi-request#117]

**Comment by yerphon** [comment]
同问

**Comment by chenjsh36** [comment]
可以通过中间件（Middleware）对 response 做转化处理

**Comment by SongBana** [comment]
Middleware 在哪个方法中 处理

**Comment by mumashanren** [comment]
@chenjsh36  具体怎么做，能否给个例子？

**Comment by SongBana** [comment]
> @chenjsh36 具体怎么做，能否给个例子？
用 jsonlint 
然后在request.js中这么处理一下
// 统一处理结果
request.use(async (ctx, next) => {
  const { req } = ctx;
  const { url, options } = req;

  await next();

`  // 处理长整型的问题
  const { res } = ctx;
  const result = jsonlint.parse(res.data);
  ctx.res = result;
  if (!result.success) {
    notification.error({
      message: `请求错误 ${result.errorMessage}: ${url}`,
      description: result.errorCode,
    });
  }
});`

**Comment by mumashanren** [comment]
问题解决了，谢谢！

**Comment by 2863416607** [comment]
@mumashanren 你是用什么解决的
