### ISSUE TITLE
cancelToken doesn't work

### ISSUE THREAD

**Issue by 1416246152** [umijs/umi-request#119]
![image](https://user-images.githubusercontent.com/21049559/77156458-60f05780-6ada-11ea-9c33-d9d183990db4.png)
接口返回的status是200
我多封装了一次处理统一报错
function ajax(url, data) {
  return new Promise(function(resolve, reject) {
    request(url, { ...data }).then(res => {
      if (res.success || res.code == 200) {
        resolve(res);
      } else {
        handleError(res);
        reject(res);
      }
    });
  });
}
export default ajax;

import ajax from '@/utils/ajax';
import Request from 'umi-request';
const CancelToken = Request.CancelToken;
const { token, cancel } = CancelToken.source();
const data = new FormData();
ajax('/api/upload', {
      method: 'POST',
      data,
      timeout: 10,
      cancelToken: token,
    })
      .then(res => {
        this.success(res);
      })
      .catch(err => {
        if (err.errorMsg) {
          cancel('超时');
        }
      });

**Comment by chenjsh36** [comment]
fetch 本身并不支持中断请求，umi-request 提供的 cancelToken 实际上是对 promise 的 reject，实际上请求依旧存在，只是 umi-request 不再理会。
