### ISSUE TITLE
Cancel is not working ???

### ISSUE THREAD

**Issue by GQMai** [umijs/umi-request#120]
使用readme中cancel的例子，发现后台HTTP请求实际并没有被取消。
请问这是正常的吗？

### Reproduction link
Case 1
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/umi-request-cancel-46y4k)

Case 2
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/umi-request-cancel-ov472)

**Comment by chenjsh36** [comment]
原生 fetch 本身不支持中断请求，umi-request 提供的 cancelToken 实际上是对 promise 的 reject，并不是真的中断请求
