### ISSUE TITLE
如果请求的接口处理时间过长，umi-request会重复发送请求？

### ISSUE THREAD

**Issue by gentleKun** [umijs/umi-request#122]
umi-request在请求接口时，如果接口处理时间 超过两分钟后会自动重新请求接口，为什么会这样 ？这个两分钟是可以设置的吗？

**Comment by xiaohuoni** [comment]
好像只有一个超时设置，没遇到有自动重新发请求的。

**Comment by chenjsh36** [comment]
不会的，除非后端返回 302 重定向到新的 URL，那么浏览器会自动发起 URL 请求。
