### ISSUE TITLE
升级到umi3.x后，interceptor里面不能获取store

### ISSUE THREAD

**Issue by huang714669** [umijs/umi-request#125]
之前在interceptor中都是以window.g_app._store.dispatch这样的方式hack访问store，现在umi3.x好像把这种方式干掉了，请问有其他替代方案吗？
说明： 业务场景是这样，同过interceptor拦截所有请求，验证token是否过期，然后尝试refresh token，refresh失败就logout，其中refresh token和logout都是需要访问store

**Comment by chenjsh36** [comment]
你好，这个应该属于 umi 升级带来的 break change，可以到 umijs 服务群问相关同学。

**Comment by citrusjunoss** [comment]
> 你好，这个应该属于 umi 升级带来的 break change，可以到 umijs 服务群问相关同学。

好像不是umi 的问题，是fetch报错了，我这边直接访问window 都无法访问
