### ISSUE TITLE
请求的配置参数没有效果

### ISSUE THREAD

**Issue by keke122765** [umijs/umi-request#126]
我想设置connection:'close'，但是几番尝试，没有效果

![image](https://user-images.githubusercontent.com/44694221/78882556-d1134d00-7a8a-11ea-955e-25ce7a1e5308.png)
![image](https://user-images.githubusercontent.com/44694221/78882609-e0929600-7a8a-11ea-8490-24ed9d1aa931.png)

**Comment by chenjsh36** [comment]
自定义头部会有限制和预检，详见[MDN文档](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Access_control_CORS)

> Fetch 规范定义了对 CORS 安全的首部字段集合，不得人为设置该集合之外的其他首部字段。
