### ISSUE TITLE
umi-request 支持微信小程序吗？

### ISSUE THREAD

**Issue by xliyq** [umijs/umi-request#127]
在微信小程序项目值使用出现错误：
Uncaught TypeError: Cannot use 'in' operator to search for 'URLSearchParams' in undefined

**Comment by birdycn** [comment]
同样的问题

**Comment by chenjsh36** [comment]
微信、支付宝小程序基于安全、约束等的考虑，屏蔽了很多浏览器环境的关键字如 window、document，导致 umi-request 目前暂不支持小程序场景，但后续会考虑作为支持的场景

**Comment by mdddj** [comment]
啥时候支持呢
