### ISSUE TITLE
typescript环境， interceptors.request.use  headers增加token

### ISSUE THREAD

**Issue by world56** [umijs/umi-request#129]
![image](https://user-images.githubusercontent.com/37354312/79289755-c62e4180-7efc-11ea-8029-d8245e8fddaf.png)

![image](https://user-images.githubusercontent.com/37354312/79289792-e231e300-7efc-11ea-9bdc-d45cc9cc32e3.png)

这种情况应当如何去定义？谢谢

**Comment by xiaochouyu2663** [comment]
解决了嘛

**Comment by world56** [comment]
> 解决了嘛

`request.interceptors.request.use((url, options) => {
    const headers = { Authorization: 'token' };
    return {
        url,
        options: {
            ...options,
            headers,
            interceptors: true
        }
    };
}, { global: true });`
这样就没问题

**Comment by world56** [comment]
> 解决了嘛
@xiaochouyu2663 
`
request.interceptors.request.use((url, options) => {
    const headers = { Authorization: 'token' };
    return {
        url,
        options: {
            ...options,
            headers,
            interceptors: true
        }
    };
}, { global: true });

`
这样就没问题
