### ISSUE TITLE
extend配置headers的时候不能调用其他方法？

### ISSUE THREAD

**Issue by shaohuatsou** [umijs/umi-request#130]
extend中配置headers的时候为什么不能调用umijs的 getLocale() 方法（该方法返回一个字符串）？

以下写法报错：
![image](https://user-images.githubusercontent.com/50793943/79307068-e247d800-7f28-11ea-9795-75f7e7c2928e.png)
![image](https://user-images.githubusercontent.com/50793943/79307076-e673f580-7f28-11ea-8510-f4f9ac9b33d6.png)

以下写法正常：
![image](https://user-images.githubusercontent.com/50793943/79307107-f390e480-7f28-11ea-8763-f1097495d21a.png)

另外请问extend是不是只会实例化一次，后面就再也不会实例了？那么我的 getLocal() 放在 extend 中是不是就不合适了（用户会切换语言）？

**Comment by coy9** [comment]
我使用了拦截器 
request.interceptors.request.use((url, options: any) => {
  options.headers.Authorization = `JWT ${localStorage.getItem('zy-token')}`
  return (
    {
      // url: `${url}&interceptors=yes`,
      options: { ...options, interceptors: true },
    }
  );
});

**Comment by chenjsh36** [comment]
1. headers 并不管是直接传 string 还是通过函数执行返回 string，看报错是 geLocale 不是函数类型导致的；
2. extend 本身是为了将固定的参数提前配置，所以只会实例化一次而不会每次都动态获取，如果参数会变，建议通过拦截器或者中间件动态加入；
