### ISSUE TITLE
希望 umi-request 支持 get 请求携带 body

### ISSUE THREAD

**Issue by Calerme** [umijs/umi-request#132]
在 restful 风格的请求中，有时 GET 请求需要携带大量的数据，必需要放到 body 里，希望 umi-request 能够支持。
在 axios 中 GET 请求是可以携带 body 的。

**Comment by chenjsh36** [comment]
HTTP GET 请求只支持在 URL 参数中携带数据，不支持在 Body 中携带，如果有大量数据需要携带，请使用 POST 方法。这个是底层协议限制的，axios 也不支持的，最终都会将数据放到 URL 的请求参数里

**Comment by JxJPu9bD** [comment]
但是postman支持这个
