### ISSUE TITLE
[Feature Request] umi-request support abort

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi-request#134]
https://github.com/github/fetch#aborting-requests

转移一个issues：https://github.com/umijs/umi/issues/2692
因为在umi那边一直没得到回复。请作者考量一下，如果不支持。请帮忙关闭了。

**Comment by chenjsh36** [comment]
非常感谢！之前主要考虑兼容性的问题加上已有的 cancelToken，所以一直没进度，这块后续支持

**Comment by chenjsh36** [comment]
umi-request 1.3.0 版本已提供 AbortController 支持中止请求
