### ISSUE TITLE
处理超时的最佳实践？

### ISSUE THREAD

**Issue by yesmeck** [umijs/umi-request#14]
1. 现在超时会调用的话会走到 `errorHandler`，那么我要在 `errorHandler` 里怎么判断这是超时错误？我现在是根据 `error.message` 里的 `timeout`，这样感觉不靠谱。
2. 现在超时触发后，如果请求回来了，这个请求的 `Promise` 还是会被 `resolve`。这个很奇怪，超时时应该已经 `reject` 掉了，为什么还会再 `resolve`?

**Comment by clock157** [comment]
1. request 会 export 一个内置的 `RequestError` ，instanceOf 这个 error.
2. 你用 errorHandler，如果没有主动 throw Error, 相对于 response 返回 undefined。
3. 超时还触发 response 拦截器算是 Bug.

超时我项目中没有应用过，要不 repo 给下，一起探寻下最佳实践~

**Comment by yesmeck** [comment]
看起来没什么问题了。。。

**Comment by vdfor** [comment]
> 1. request 会 export 一个内置的 `RequestError` ，instanceOf 这个 error.

请问下 export 的 RequestError 是什么？没有发现这个
