### ISSUE TITLE
node 环境 timeout 好像有问题？

### ISSUE THREAD

**Issue by crazyair** [umijs/umi-request#141]
```js
const umi = require('umi-request');

const http = umi.extend({ timeout: 10000 });
const func = async () => {
  await http.get('http://baidu.com');
  console.log('ok');
};

func();

```

延时设置 10s ，`node index.js` 执行后就 10s 才结束。

**Comment by crazyair** [comment]
?

**Comment by crazyair** [comment]
有人吗？

**Comment by chenjsh36** [comment]
Node.js 中的 io 句柄和 setTimeout/setInterval/setImmediate 默认都会阻止进程退出。
当设置了 timeout 后，umi-request 会设定一个定时器，在 timeout 秒后如果接口还没响应则 reject，而当 request 在 timeout 内响应时，由于计时器还在，导致 NodeJS 程序会等待计时器触发执行后再退出。

**Comment by crazyair** [comment]
> Node.js 中的 io 句柄和 setTimeout/setInterval/setImmediate 默认都会阻止进程退出。
> 当设置了 timeout 后，umi-request 会设定一个定时器，在 timeout 秒后如果接口还没响应则 reject，而当 request 在 timeout 内响应时，由于计时器还在，导致 NodeJS 程序会等待计时器触发执行后再退出。

没有说怎么结局？还有要怎么用？不加的话，如果超时就卡主半天了，加的话，每个请求都 3 秒
