### ISSUE TITLE
服务端返回302 时，无法获取到response 状态码

### ISSUE THREAD

**Issue by johnzhou2011** [umijs/umi-request#144]

**Comment by chenjsh36** [comment]
可参考 [fetch-MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/WindowOrWorkerGlobalScope/fetch) 文档关于 redirect 配置，对于服务端返回 302，默认是会自动重定向，前端无法捕获，解决方案可参考[fetch捕获重定向302/301](https://blog.csdn.net/weixin_33711647/article/details/88039321)

**Comment by ziscloud** [comment]
`request.interceptors.response.use(response => {
  if (response.redirected) {
    window.location.href = response.url;
  }
  return response;
});`

这样处理就可以了
