### ISSUE TITLE
用request请求responseType为arrayBuffer的接口问题

### ISSUE THREAD

**Issue by Lmangoxx** [umijs/umi-request#147]
用request请求responseType为arrayBuffer的接口时，接口可以正常访问，数据流也可以返回给前端，但是request一直触发全局errorHandler，导致前端拿不到后端返回的数据流

**Comment by mo-om** [comment]
> 用request请求responseType为arrayBuffer的接口时，接口可以正常访问，数据流也可以返回给前端，但是request一直触发全局errorHandler，导致前端拿不到后端返回的数据流

我将responseType设置为blob也同样遇到了该问题

**Comment by chenjsh36** [comment]
能提供 demo 和截图吗？

**Comment by Lmangoxx** [comment]
已经解决了，谢谢每个人

**Comment by yuu2lee4** [comment]
@mo-om  怎么解决的呢
