### ISSUE TITLE
prefix功能和url绝对路径一起用有冲突

### ISSUE THREAD

**Issue by diemus** [umijs/umi-request#154]
version 1.2.19

prefix=“/api/v1”
url="http://xxxx.com/test"

期望url：
url="http://xxxx.com/test"

实际url:
url="http://localhost:3000/api/v1http://xxxx.com/test"

**Comment by chenjsh36** [comment]
是的，prefix 逻辑就是在请求 URL 设置统一前缀，如果需要使用绝对路径，建议对这类请求统一单独设置 prefix 为空进行覆盖：

```
let request = extend({
  prefix: '/api/v1';
})

request('http://xxxx.com/test', {
  prefix: '', // 对绝对路径做覆盖解决冲突
})
```
