### ISSUE TITLE
TypeError: _umiRequest.AbortController is not a constructor

### ISSUE THREAD

**Issue by lishaoh** [umijs/umi-request#156]
umi-request
版本；1.3.3
没有AbortController实例

**Comment by chenjsh36** [comment]
Abortcontroller 在低版本中出现不兼容问题，暂时去掉了，如果你的应用场景没有低版本浏览器，可以用 1.3.2 版本

**Comment by crownclownwl** [comment]
我也遇到了这个问题了 ，

**Comment by crownclownwl** [comment]
我的版本是 1.3.5 也没有这个这个实例

**Comment by 123456wjw** [comment]
> Abortcontroller 在低版本中出现不兼容问题，暂时去掉了，如果你的应用场景没有低版本浏览器，可以用 1.3.2 版本

![image](https://user-images.githubusercontent.com/37201576/103254222-74ace080-49bf-11eb-9382-ce1bef32b10d.png)
![image](https://user-images.githubusercontent.com/37201576/103254234-7ecedf00-49bf-11eb-84f2-47f62edfeced.png)
1.3.2版本仍然出现这个问题
