### ISSUE TITLE
请求下载文件流如何获取后端设置的 文件名称

### ISSUE THREAD

**Issue by wenJonSnow** [umijs/umi-request#159]
![image](https://user-images.githubusercontent.com/24515796/83943216-e90a1180-a82c-11ea-8d08-c9b570542ca5.png)

  
xhr 是这种方式   xhr.getResponseHeader('content-disposition'); 

umi-request 如何获取文件名称

**Comment by whatwewant** [comment]
底层是fetch, 所以用fetch获取response header的方法就可以了

```
response.headers.get('content-disposition')
```

**Comment by 495640129** [comment]
> 底层是fetch, 所以用fetch获取response header的方法就可以了
> 
> ```
> response.headers.get('content-disposition')
> ```

不行啊，设置responseType=blob之后，response是一个Blob对象。

**Comment by rangyf** [comment]
同问，只要能拿到header就行，问题就是怎么拿，只剩一个Blob对象了

**Comment by heartrainy** [comment]
添加getResponse这个属性，改成true,就可以既返回blob，又返回response了

**Comment by zula1994** [comment]
> 添加getResponse这个属性，改成true,就可以既返回blob，又返回response了

headers还是为空

**Comment by 495640129** [comment]
> > 添加getResponse这个属性，改成true,就可以既返回blob，又返回response了
> 
> headers还是为空

是的，headers还是空

**Comment by xrkffgg** [comment]
额。。。后端直接传个字段不就得了

**Comment by 495640129** [comment]
> 额。。。后端直接传个字段不就得了

后端返回的是字节流，HttpServletResponse header里面放文件名:
Content-disposition: attachment;filename=demo.xlsx

**Comment by liucong1** [comment]
request
      .get('/xxx/xxx', {
        getResponse: true,
      })

记得让后端配置 Access-Control-Allow-Headers ，不然拿不到content-disposition

**Comment by baobeidaodao** [comment]
responseType: 'blob',
parseResponse: false

response.headers.get('content-disposition')

**Comment by BongBongBang** [comment]
> > 额。。。后端直接传个字段不就得了
> 
> 后端返回的是字节流，HttpServletResponse header里面放文件名:
> Content-disposition: attachment;filename=demo.xlsx
> 
> 通过这个方法拿到了文件名，谢谢!
> response.headers.get('Content-disposition')

我这里通过response获取Headers是空的，大佬是怎么解决的？

**Comment by BongBongBang** [comment]
> > > 额。。。后端直接传个字段不就得了
> > 
> > 
> > 后端返回的是字节流，HttpServletResponse header里面放文件名:
> > Content-disposition: attachment;filename=demo.xlsx
> > 通过这个方法拿到了文件名，谢谢!
> > response.headers.get('Content-disposition')
> 
> 我这里通过response获取Headers是空的，大佬是怎么解决的？

通过浏览器查看输出的对象，headers确实空的，不用管，直接调用response.headers.get(...)方法即可，会有返回的

**Comment by mx52jing** [comment]
感谢上面各位回答，请求时候加上`getResponse`和`responseType`可以获得文件流，亲测有效

request
  .get('/xxx/xxx', {
     getResponse: true,
     responseType: 'blob',
  })

响应的时候可能也要处理下，之前普通接口返回时，`响应拦截器`里面是`response.clone().json();`，这里需要修改下直接返回`response`即可

export const responseInterceptors = async (response: Response, options: RequestOptionsInit) => {
  if (!response) {
    message.error('您的网络发生异常，无法连接服务器');
    return;
  }
  if (options.responseType === 'blob') {
    // 处理二进制文件
    return response;
  }
  const data = await response.clone().json();
  // xxxxxxxxxxxxx 其他处理逻辑
 }

**Comment by mx52jing** [comment]
感谢上面各位回答，请求时候额外参数加上`getResponse`和`responseType`可以获得文件流，亲测有效

```javascript
request
  .get('/xxx/xxx', {
    getResponse: true,
    responseType: 'blob',
  })
```

响应的时候可能也要处理下，之前普通接口返回时，响应拦截器里面是`response.clone().json()`，这里需要修改下直接返回response即可

```javascript
export const responseInterceptors = async (response: Response, options: RequestOptionsInit) => {
    if (!response) {
    message.error('您的网络发生异常，无法连接服务器');
    return;
    }
    if (options.responseType === 'blob') {
    // 处理二进制文件
    return response;
    }
    const data = await response.clone().json();
    // xxxxxxxxxxxxx 其他处理逻辑
}
```
