### ISSUE TITLE
全局拦截如何区分接口是否要加token

### ISSUE THREAD

**Issue by zywkuo** [umijs/umi-request#160]
目前request没有办法进行自定义字段值返回，项目需求为，有的需要加token验证，有的不需要加，不想每个接口进行token添加，想在request.js进行统一处理，请问如何进行区分处理。

**Comment by fengmumu1** [comment]
不是有拦截器吗？直接再那里添加不行吗？

**Comment by fengmumu1** [comment]
在请求或响应被 then 或 catch 处理前拦截它们。

全局拦截器
// request拦截器, 改变url 或 options.
request.interceptors.request.use((url, options) => {
  return {
    url: `${url}&interceptors=yes`,
    options: { ...options, interceptors: true },
  };
});

// 和上一个相同
request.interceptors.request.use(
  (url, options) => {
    return {
      url: `${url}&interceptors=yes`,
      options: { ...options, interceptors: true },
    };
  },
  { global: true }
);

// response拦截器, 处理response
request.interceptors.response.use((response, options) => {
  const contentType = response.headers.get('Content-Type');
  return response;
});

文档写的还是比较清楚哈，不想用话 也可以用全局插件来处理啦

**Comment by zywkuo** [comment]
是的，就是在拦截器里进行统一的token添加，目前项目需求是，部分接口不需要添加token验证，部分接口添加，就需要进行判断处理，目前我是这么处理的。
通过接口传入特殊字段，在拦截器进行拦截，存在此特殊字段值，不添加token，不存在，进行token添加处理。
<img width="430" alt="WX20200618-103326@2x" src="https://user-images.githubusercontent.com/21994183/84971682-ddcdb480-b14f-11ea-92c9-bd909dbb3d79.png">
<img width="572" alt="WX20200618-103549@2x" src="https://user-images.githubusercontent.com/21994183/84971687-e0300e80-b14f-11ea-80ab-79fcdcf87c0e.png">
