### ISSUE TITLE
get请求怎么传递数组

### ISSUE THREAD

**Issue by Cliff-Rhine** [umijs/umi-request#165]
```
request(url, { params: { select: [1,2,3] } })
```
发送get请求时，
请求的url变成了`url?select=1&select=2&select=3`这个样子，php后台就只能接受到select=3，
之前用axios的时候请求url是`url?select[]=1&select[]=2&select[]=3`，php后台能正确识别为数组，请问是要修改什么配置参数么？

**Comment by Cliff-Rhine** [comment]
解决了
```
import Qs from 'qs'
request(url, {
  params: { select: [1,2,3] },
  paramsSerializer: function (params) {
    return Qs.stringify(params, { arrayFormat: 'brackets' })
  },
})
```

**Comment by dmdoit** [comment]
哈哈，你这个方法可行，不过我写的要更简短一点
```
import request from '../utils/request';
import { stringify } from 'qs';
export async function queryList(params) {
  return request(`/api/list?${stringify(params, { arrayFormat: 'brackets' })}`);
}
```

**Comment by Cliff-Rhine** [comment]
> 哈哈，你这个方法可行，不过我写的要更简短一点
> 
> ```
> import request from '../utils/request';
> import { stringify } from 'qs';
> export async function queryList(params) {
>   return request(`/api/list?${stringify(params, { arrayFormat: 'brackets' })}`);
> }
> ```

666
