### ISSUE TITLE
form请求问题

### ISSUE THREAD

**Issue by DXDZY** [umijs/umi-request#17]
requestType:'form',设置这种后，请求参数为数组时，请求参数没有下标，变成这样
![image](https://user-images.githubusercontent.com/15250383/51361763-02150400-1b0c-11e9-842c-e5aeb3ff6f17.png)
但是后端不识别，如何让请求参数变成下边这种带下标的结构
![image](https://user-images.githubusercontent.com/15250383/51361900-78196b00-1b0c-11e9-8c3b-0ab430d4691b.png)

**Comment by clock157** [comment]
我测试这种 node 的后端是可以识别，你的后端是什么？

**Comment by DXDZY** [comment]
@clock157 我这边后端是php，可能是后端的问题，我再问问后端，谢啦

**Comment by zlyyyy** [comment]
想问下问题怎么解决的，我这边get也遇到了这个问题
