### ISSUE TITLE
Refresh Token for umi request interceptors response

### ISSUE THREAD

**Issue by xXAvoraXx** [umijs/umi-request#181]
I use tokens as authorization, when the token expires, I want to create a new token using the refresh token. I can do this with the axios library but I couldn't find how to do it with umi request. Anyone translate the code sample given below to an umi request interceptor example?

this axios interceptors response for my refresh token operation.

```
      let isRefreshing: boolean = false;
      let failedQueue: any = [];
    
      const processQueue = (error: any, token: any = null) => {
        failedQueue.forEach((prom: any) => {
          if (error) {
            prom.reject(error);
          } else {
            prom.resolve(token);
          }
        });
    
        failedQueue = [];
      };
    
    axios.interceptors.response.use(
        async response => {
          return response;
        },
        async error => {
          debugger;
          const originalRequest = error.config;
          if (error.response) {
            const status = error.response.status;
            const refreshToken = getStoredUserAuth().refreshToken;
            if (status === 401 && !originalRequest._retry) {
              if (isRefreshing) {
                return new Promise(function(resolve, reject) {
                  failedQueue.push({ resolve, reject });
                })
                  .then(token => {
                    originalRequest.headers["Authorization"] = "Bearer " + token;
                    return axios(originalRequest);
                  })
                  .catch(err => {
                    return Promise.reject(err);
                  });
              }
    
              originalRequest._retry = true;
              isRefreshing = true;
    
              return new Promise(function(resolve, reject) {
                refreshAccessToken(refreshToken)
                  .then(response => {
                    if (response.status === 200) {
                      if (response.data.token) {
                        setAuthStatus(response.data);
                        axios.defaults.headers.common["Authorization"] =
                          "Bearer " + response.data.token;
                        originalRequest.headers["Authorization"] =
                          "Bearer " + response.data.token;
                      }
                      processQueue(null, response.data.token);
                      resolve(axios(originalRequest));
                    } else {
                      throw new Error();
                    }
                  })
                  .catch(err => {
                    //console.log(err);
                    failedQueue = [];
                    setUnauthStatus();
                    source.cancel("Session time out");
                    processQueue(err, null);
                    reject(err);
                  })
                  .then(() => {
                    isRefreshing = false;
                  });
              });
            }
          } else {
            debugger;
            errorHandler(error);
          }
          return Promise.reject(error);
        }
      );
```

I use to ant design pro V5 version, so I've tried to refresh token with umi request but I could'nt do it, As in the axios library, I cannot write for umi request, I cannot establish its logic. So can anyone write the same example (axios.interceptors.response) above for umi request?

I tried to below code but gave error, not perfect correctly
 ```
const refreshTime = 10000;
let cacheRequest: any[] = [];
let guoqi = true;
let ispending = false;

const requestInterceptors = (url: string, options: RequestOptionsInit) => {
  const token = tokenService.parse()?.token;
  if (token) {
    const headers = {
      Authorization: `Bearer ${token}`,
    }
    debugger;
    if (url === 'https://localhost:44326/api/auth/createAccessTokenByRefreshToken') {
      return {
        url,
        options: { ...options, headers },
      };
    }
    const decodeToken: any = jwt_decode(token);
    const { exp } = decodeToken;
    const maxTime = exp * 1000 + refreshTime;
    const nowTime = new Date().getTime();
    if (nowTime >= maxTime) {
      // token过期，而且延期token也过去了，那么，清空你的数据，直接返回登录，不允许操作了
      // console.log('超时了')
      tokenService.remove();
      window.location.href = '/user/login'
       return; // that line gave error
    }
    if (nowTime >= exp * 1000) {
      // 只是过期了，那就去拿新的token
      if (ispending) {
        // 如果正在发送中，此请求就等一会吧，生成一个Promise 等新token返回的时候，我再resolve
      } else {
        // 如果没发送，立刻改为发送状态
        ispending = true;
        refreshAccessToken(tokenService.parse()!.refreshToken)
          .then(res => {
            debugger;
            if (res) {
              if (res.token) {
                // setAuthStatus(res.data);
                ispending = false;
                tokenService.save(res);
                cacheRequest.map(cb => cb());
              }
            } else {
              throw new Error();
            }
          })

      }
      return new Promise<>((resolve, reject) => { // that line gave error
        cacheRequest.push(() => {
          resolve()
        })
       });
    }
    return {
      url,
      options: { ...options, headers },
    };
  }

  return {
    url,
    options: { ...options },
  };
}
export const request: RequestConfig = {
  errorHandler,
  headers: {
    'Authorization': `Bearer ${tokenService.parse()?.token}`
  },
  requestInterceptors: [requestInterceptors],
  // responseInterceptors: [responseInterceptors]
};
```

**Comment by xXAvoraXx** [comment]
I need help ++++++

**Comment by sxinle** [comment]
这样行不？

```
const errorHandler = error => {
  const { request: req, response } = error;
  if (response && response.status) {
    if (response.status === 401) {
      // ... 做refreshToken的操作,用拿到的新token,修改req的header: {Authorization:'newToken'}
      // 然后把之前的请求“重放一遍”
      return requestFunc(req.url, req.options);
    }
  }
};

const requestFunc = extend({
  prefix: hostIp,
  errorHandler,
});

**Comment by xXAvoraXx** [comment]
> Bu çalışıyor mu?
> 
> ```
> const errorHandler = error => {
>   const { request: req, response } = error;
>   if (response && response.status) {
>     if (response.status === 401) {
>       // ... 做refreshToken的操作,用拿到的新token,修改req的header: {Authorization:'newToken'}
>       // 然后把之前的请求“重放一遍”
>       return requestFunc(req.url, req.options);
>     }
>   }
> };
> 
> const requestFunc = extend({
>   prefix: hostIp,
>   errorHandler,
> });
> ```

not work because of const { request: req, response } = error;
I cant reach request in error.

```
const errorHandler = (error: ResponseError) => {
  const { response } = error;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;
    if (status === 401) {
      return request()
    }
    notification.error({
      message: `${status}: ${url}`,
      description: errorText,
    });
  }

  if (!response) {
    notification.error({
      description: '-',
      message: '-',
    });
  }
  throw error;
};

```

**Comment by richagain** [comment]
> > 这样行不？
> > ```
> > const errorHandler = error => {
> >   const { request: req, response } = error;
> >   if (response && response.status) {
> >     if (response.status === 401) {
> >       // ... 做refreshToken的操作,用拿到的新token,修改req的header: {Authorization:'newToken'}
> >       // 然后把之前的请求“重放一遍”
> >       return requestFunc(req.url, req.options);
> >     }
> >   }
> > };
> > 
> > const requestFunc = extend({
> >   prefix: hostIp,
> >   errorHandler,
> > });
> > ```
> 
> not work because of const { request: req, response } = error;
> I cant reach request in error.
> 
> ```
> const errorHandler = (error: ResponseError) => {
>   const { response } = error;
>   if (response && response.status) {
>     const errorText = codeMessage[response.status] || response.statusText;
>     const { status, url } = response;
>     if (status === 401) {
>       return request()
>     }
>     notification.error({
>       message: `${status}: ${url}`,
>       description: errorText,
>     });
>   }
> 
>   if (!response) {
>     notification.error({
>       description: '-',
>       message: '-',
>     });
>   }
>   throw error;
> };
> ```

Please try this:

`const errorHandler = async (error: {
  request: any;
  response: Response;
}): Promise<Response> => {
  const { request, response } = error;
  console.log(request);
}`

**Comment by richagain** [comment]
hi, for anyone who is looking for refreshing token after gettting http 401, you might refer to my codes.

const errorHandler = async (error: {
  request: any;
  response: Response;
}): Promise<Response> => {
  const { response } = error;
  const req = error.request;
  if (response && response.status) {
    const errorText = codeMessage[response.status] || response.statusText;
    const { status, url } = response;

    if (status === 401 && req) {
      const {
        url,
        options: { method, data },
      } = req;
      const jwt: Jwt = await secureLoad(Storage.JWT);
      const jwtStatus = await getJwtStatus(jwt);
      if (jwtStatus === "expired") {
        const response = await refresh(jwt);
        if (response.jwt && response.jwt.expires_in) {
          await secureSaveJWT(response.jwt);
          const responseRetry = await request(url, {
            method,
            data,
          });
          return responseRetry;
        }
      }
      return response;
    }

    // notification.error({
    //   message: `请求错误 ${status}: ${url}`,
    //   description: errorText,
    // });
  } else if (!response) {
    // notification.error({
    //   description: '您的网络发生异常，无法连接服务器',
    //   message: '网络异常',
    // });
  }
  return response;
};

**Comment by xXAvoraXx** [comment]
> hi, for anyone who is looking for refreshing token after gettting http 401, you might refer to my codes.
> 
> const errorHandler = async (error: {
> request: any;
> response: Response;
> }): Promise => {
> const { response } = error;
> const req = error.request;
> if (response && response.status) {
> const errorText = codeMessage[response.status] || response.statusText;
> const { status, url } = response;
> 
> ```
> if (status === 401 && req) {
>   const {
>     url,
>     options: { method, data },
>   } = req;
>   const jwt: Jwt = await secureLoad(Storage.JWT);
>   const jwtStatus = await getJwtStatus(jwt);
>   if (jwtStatus === "expired") {
>     const response = await refresh(jwt);
>     if (response.jwt && response.jwt.expires_in) {
>       await secureSaveJWT(response.jwt);
>       const responseRetry = await request(url, {
>         method,
>         data,
>       });
>       return responseRetry;
>     }
>   }
>   return response;
> }
> 
> // notification.error({
> //   message: `请求错误 ${status}: ${url}`,
> //   description: errorText,
> // });
> ```
> 
> } else if (!response) {
> // notification.error({
> // description: '您的网络发生异常，无法连接服务器',
> // message: '网络异常',
> // });
> }
> return response;
> };

**I thought about your solution before, but what if 2 error messages (from two diff request) are returned at the same time?**

**This my solution,**

```
let isRefreshing: boolean = false;
let failedQueue: any = [];

const processQueue = (error: any, token: any = null) => {
  failedQueue.forEach((prom: any) => {
    if (error) {
      prom.reject(error);
    } else {
      prom.resolve(token);
    }
  });

  failedQueue = [];
};
// interface RequestOptionsExtend extends RequestOptionsInit {
//   retry?: boolean;
// }
const responseInterceptors = (response: Response, options: RequestOptionsInit) => {
  const { status } = response;
  // const originalRequest: RequestOptionsExtend = options;
  const refreshToken = tokenService.parse()?.refreshToken;

  if (status === 401) {
    if (isRefreshing) {
      return new Promise<Response>((resolve, reject) => {
        failedQueue.push({ resolve, reject });
      })
        .then(token => {
          return Reqs(response.url, { ...options, headers: { Authorization: `Bearer ${token}` } });
        })
        .catch(err => {
          return Promise.reject(err);
        });
    }

    // originalRequest.retry = true;
    isRefreshing = true;

    if (tokenService.check()) {
      return new Promise<Response>((resolve, reject) => {
        refreshAccessToken(refreshToken!)
          .then(res => {
            if (res) {
              if (res.token) {
                tokenService.save(res);
              }
              processQueue(null, res.token);
              resolve(Reqs(response.url, { ...options, headers: { Authorization: `Bearer ${res.token}` } }));
            } else {
              throw new Error();
            }
          })
          .catch(err => {
            failedQueue = [];
            tokenService.remove();
            cancel("Oturum süresi doldu.");
            processQueue(err, null);
            reject(err);
          })
          .then(() => {
            isRefreshing = false;
          });
      });
    }


  }

  return response;
}
```

**Comment by richagain** [comment]
> > hi, for anyone who is looking for refreshing token after gettting http 401, you might refer to my codes.
> > const errorHandler = async (error: {
> > request: any;
> > response: Response;
> > }): Promise => {
> > const { response } = error;
> > const req = error.request;
> > if (response && response.status) {
> > const errorText = codeMessage[response.status] || response.statusText;
> > const { status, url } = response;
> > ```
> > if (status === 401 && req) {
> >   const {
> >     url,
> >     options: { method, data },
> >   } = req;
> >   const jwt: Jwt = await secureLoad(Storage.JWT);
> >   const jwtStatus = await getJwtStatus(jwt);
> >   if (jwtStatus === "expired") {
> >     const response = await refresh(jwt);
> >     if (response.jwt && response.jwt.expires_in) {
> >       await secureSaveJWT(response.jwt);
> >       const responseRetry = await request(url, {
> >         method,
> >         data,
> >       });
> >       return responseRetry;
> >     }
> >   }
> >   return response;
> > }
> > 
> > // notification.error({
> > //   message: `请求错误 ${status}: ${url}`,
> > //   description: errorText,
> > // });
> > ```
> > 
> > 
> > } else if (!response) {
> > // notification.error({
> > // description: '您的网络发生异常，无法连接服务器',
> > // message: '网络异常',
> > // });
> > }
> > return response;
> > };
> 
> **I thought about your solution before, but what if 2 error messages (from two diff request) are returned at the same time?**
> 
> **This my solution,**
> 
> ```
> let isRefreshing: boolean = false;
> let failedQueue: any = [];
> 
> const processQueue = (error: any, token: any = null) => {
>   failedQueue.forEach((prom: any) => {
>     if (error) {
>       prom.reject(error);
>     } else {
>       prom.resolve(token);
>     }
>   });
> 
>   failedQueue = [];
> };
> // interface RequestOptionsExtend extends RequestOptionsInit {
> //   retry?: boolean;
> // }
> const responseInterceptors = (response: Response, options: RequestOptionsInit) => {
>   const { status } = response;
>   // const originalRequest: RequestOptionsExtend = options;
>   const refreshToken = tokenService.parse()?.refreshToken;
> 
>   if (status === 401) {
>     if (isRefreshing) {
>       return new Promise<Response>((resolve, reject) => {
>         failedQueue.push({ resolve, reject });
>       })
>         .then(token => {
>           return Reqs(response.url, { ...options, headers: { Authorization: `Bearer ${token}` } });
>         })
>         .catch(err => {
>           return Promise.reject(err);
>         });
>     }
> 
>     // originalRequest.retry = true;
>     isRefreshing = true;
> 
>     if (tokenService.check()) {
>       return new Promise<Response>((resolve, reject) => {
>         refreshAccessToken(refreshToken!)
>           .then(res => {
>             if (res) {
>               if (res.token) {
>                 tokenService.save(res);
>               }
>               processQueue(null, res.token);
>               resolve(Reqs(response.url, { ...options, headers: { Authorization: `Bearer ${res.token}` } }));
>             } else {
>               throw new Error();
>             }
>           })
>           .catch(err => {
>             failedQueue = [];
>             tokenService.remove();
>             cancel("Session time out.");
>             processQueue(err, null);
>             reject(err);
>           })
>           .then(() => {
>             isRefreshing = false;
>           });
>       });
>     }
> 
> 
>   }
> 
>   return response;
> }
> ```

I saw you had failed queue array. You might put a condition in the loop, in the case if the retry of failed queue got none 200 status, the loop stops. You then define a threshold to loop again.

**Comment by xXAvoraXx** [comment]
what exactly mean loop, I haven't any loop ? can you edit the code ?

**Comment by richagain** [comment]
> what exactly mean loop, I haven't any loop ? can you edit the code ?

I referred to your codes and there was a block of codes as below:

let isRefreshing: boolean = false;
let failedQueue: any = [];

const processQueue = (error: any, token: any = null) => {
  failedQueue.forEach((prom: any) => {
    if (error) {
      prom.reject(error);
    } else {
      prom.resolve(token);
    }
  });

  failedQueue = [];
};

I guess you put all failed requests to failedQueue and it is an array. Let say you have two different request encountered http 401 error at the same time. What you would do is to:

1. push these two failed request into failedQueue (redux or other statement). And not don't let them re-try in the response interceptor.
2. running a tasker to attemp failedQueue request one by one. Let say item 0 failed, it would be re-assigned to failedQueue at last position. Then excute item 1 and so on.
3. if item 1 attempts successfully, you refresh you token, then re-try item 2 and so on to clear the failedQueue.

I think you use failedQueue in this kind of purpose at the first place.

**Comment by xXAvoraXx** [comment]
> > what exactly mean loop, I haven't any loop ? can you edit the code ?
> 
> I referred to your codes and there was a block of codes as below:
> 
> let isRefreshing: boolean = false;
> let failedQueue: any = [];
> 
> const processQueue = (error: any, token: any = null) => {
> failedQueue.forEach((prom: any) => {
> if (error) {
> prom.reject(error);
> } else {
> prom.resolve(token);
> }
> });
> 
> failedQueue = [];
> };
> 
> I guess you put all failed requests to failedQueue and it is an array. Let say you have two different request encountered http 401 error at the same time. What you would do is to:
> 
> 1. push these two failed request into failedQueue (redux or other statement). And not don't let them re-try in the response interceptor.
> 2. running a tasker to attemp failedQueue request one by one. Let say item 0 failed, it would be re-assigned to failedQueue at last position. Then excute item 1 and so on.
> 3. if item 1 attempts successfully, you refresh you token, then re-try item 2 and so on to clear the failedQueue.
> 
> I think you use failedQueue in this kind of purpose at the first place.

sometimes it falls into an endless refresh cycle.

**Comment by xXAvoraXx** [comment]
@richagain I'm trying your solution, but it doesn't handle the error returned from any request. ErrorHandler works only in app.tsx. How did you solve this problem?

**Comment by manondidi** [comment]
> @richagain I'm trying your solution, but it doesn't handle the error returned from any request. ErrorHandler works only in app.tsx. How did you solve this problem?
do you solve this problem? how ? thx

**Comment by manondidi** [comment]
i think i solve this problem

`request.interceptors.request.use(async (url, options) => {

  let token = localStorage.getItem("token");
  const headers = {
    'token': token,
    'X-tenant': "default"
  };
  return (
    {
      url: url,
      options: {...options, headers: headers},
    }
  );
})
request.interceptors.response.use(async (response, options) => {
  const result = await response.clone().json()
  const {code, message, data} = result;
  if (code === 0) {
    return data;
  } else if (code === 400402) {
    let tokenData = await refreshToken()
    localStorage.setItem("token", tokenData.token)
    localStorage.setItem("refresh-token", tokenData.refreshToken)
    return retry(response, options)
  } else if (code === 400403) {
    //跳转登录页
    history.replace({
      pathname: '/user/login',
      search: stringify({
        redirect: window.location.href,
      }),
    });
  } else {
    throw new Error(message);
  }
});

const retry = (response, options) => {
  return request(response.url, options)
}`

**Comment by xXAvoraXx** [comment]
@manondidi 

```
let isRefreshing: boolean = false;
let failedQueue: any = [];

const processQueue = (error: any, token: any = null) => {
  failedQueue.forEach((prom: any) => {
    if (error) {
      prom.reject(error);
    } else {
      prom.resolve(token);
    }
  });

  failedQueue = [];
};

const responseInterceptors = (response: Response, options: RequestOptionsInit) => {
  const { status } = response;
  const refreshToken = tokenService.parse()?.refreshToken;

  if (status === 401) {
    if (isRefreshing) {
      return new Promise<Response>((resolve, reject) => {
        failedQueue.push({ resolve, reject });
      })
        .then((token) => {
          return Reqs(response.url, { ...options, headers: { Authorization: `Bearer ${token}` } });
        })
        .catch((err) => {
          return Promise.reject(err);
        });
    }

    // originalRequest.retry = true;
    isRefreshing = true;

    if (tokenService.check()) {
      return new Promise<Response>((resolve, reject) => {
        refreshAccessToken(refreshToken!)
          .then((res) => {
            if (res) {
              if (res.token) {
                tokenService.save(res);
              }
              processQueue(null, res.token);
              resolve(
                Reqs(response.url, {
                  ...options,
                  headers: { Authorization: `Bearer ${res.token}` },
                }),
              );
            } else {
              throw new Error();
            }
          })
          .catch((err) => {
            failedQueue = [];
            tokenService.remove();
            cancel('Oturum süresi doldu.');
            processQueue(err, null);
            reject(err);

            const { redirect } = getPageQuery();
            // Note: There may be security issues, please note
            if (window.location.pathname !== '/user/login' && !redirect) {
              history.replace({
                pathname: '/user/login',
                search: stringify({
                  redirect: window.location.href,
                }),
              });
            }

            // history.push('/user/login');
            notification.error({
              message: 'Session time out',
              description: 'your redirected to login page.',
            });
          })
          .then(() => {
            isRefreshing = false;
          });
      });
    }
  }

  return response;
};
```

**Comment by h1nson** [comment]
Here is my code:

```
requestInterceptors: [
    async (config: RequestOptions) => {
      // 拦截请求配置，进行个性化处理。
      let token = Cookies.get(HKMS_ACCESS_TOKEN);

      //refresh token logic
      const { url } = config;
      if (token && url !== '/api/tokenAuth/refresh' && url !== '/api/tokenAuth/authenticate') {
        const { exp } = jwtDecode(token);
        const expTime = exp! * 1000;
        const nowTime = new Date().getTime();
        if (nowTime >= expTime) {
          //token expired, refresh token
          if (!isPending) {
            isPending = true;

            getRefreshToken().then((newToken) => {
              isPending = false;

              _cacheRequest.map((cb) => cb(newToken, url));
              _cacheRequest = [];
            });
          }
          return new Promise((resolve) => {
            _cacheRequest.push((latestToken: string) => {
              config.headers = { Authorization: `Bearer ${latestToken}` };
              resolve(config);
            });
          });
        }
      }

      const headers = {
        Authorization: `Bearer ${token}`,
      };
      return { ...config, headers };
    },
```
