### ISSUE TITLE
拦截器如何修改Response

### ISSUE THREAD

**Issue by sanwanliu** [umijs/umi-request#183]
服务器返回按固定格式{code:200,"msg":"ok",data:{}}，我想利用拦截器将data提取出来返回

**Comment by AsuraZhu** [comment]
可以自己返回个primise  return  new Promise((resolve)=>resolve({}))

**Comment by sanwanliu** [comment]
> 可以自己返回个primise return new Promise((resolve)=>resolve({}))


感谢大佬！试了一下，可以达到预期


![image](https://user-images.githubusercontent.com/23079982/91281265-6f921780-e7ba-11ea-8f23-892ea7425085.png)

**Comment by sanwanliu** [comment]
不过会报这个错误 
Type '(response: Response) => Promise<unknown>' is not assignable to type 
可以直接修改response，并返回response吗 @AsuraZhu

**Comment by SmartWrh** [comment]
> 不过会报这个错误
> Type '(response: Response) => Promise' is not assignable to type
> 可以直接修改response，并返回response吗 @AsuraZhu

额，所以怎么解决这个类型报错呀，-。-

**Comment by kalavt** [comment]
所以呢? 怎么才能修改Response data?

**Comment by kalavt** [comment]
```
const middleware = async (ctx, next) => {
  // console.log('before');
  await next();
  const { res } = ctx;
  if (res.data) {
    res.data.forEach((item) => {
      Object.assign(item, item.attributes);
    });
  }

  // pro table request
  res.success = true;
  res.total = res.meta.total;
};
```
