### ISSUE TITLE
Reading response body in the error handler - how?

### ISSUE THREAD

**Issue by KrishnaPG** [umijs/umi-request#242]
In the umi ant-pro-layout template, the error handler is configured as below:
````js
const errorHandler = (error: ResponseError) => {
  const { response } = error;

  if (response && response.status) {
    const { status, statusText, url } = response;

   // .... rest of the code
}
````

When using JSON-RPC we send error messages as part of the response body. However, reading the response requires a promise() to be returned. And it does not look like the `errorHandler` intercept supports the promise return value.

Q: How to read the response body in the error handler, so that we can display the response body in the notification ?

**Comment by KrishnaPG** [comment]
Is there a way the response can be asked to give body as a object (e.g. json object) and not as stream?

Axios gives response body as an object and we can ready the body object in the interceptor. Since `umi request` gives response body as stream, it is not possible to read the body in the interceptor (since error interceptor does not seem to support promises). 

Any help or example that illustrates using response body inside the error handler would be of great value. Thank you.

**Comment by erlei22** [comment]
i use sentry to captureException and setExtra response ,and i meet [object Response]     
 so do you have any good function to make it to be json object

**Comment by aquibbaig** [comment]
Same issue, even `getResponse: true` doesn't work for me
