### ISSUE TITLE
Newly published umi-request@1.3.6 not ES5 compatible/新发布的umi-request@1.3.6不再是ES5兼容的

### ISSUE THREAD

**Issue by shotforsky** [umijs/umi-request#247]
项目中使用到了UglifyJS对代码做压缩，项目构建一直正常，直到最近更新发布了 umi-request@1.3.6，构建失败了

**我的webpack配置中uglify相关**：
```javascript
// webpack.config.js
webpackConfig.plugins.push(
    new webpack.optimize.UglifyJsPlugin({
        comments: false,
        compress: {
            warnings: false,
        },
        except: ['$super', '$', 'exports', 'require'],
    }),
);
```

**构建报错**：
![image](https://user-images.githubusercontent.com/14038117/119317238-721e9080-bcaa-11eb-936e-d1f39308de34.png)

报错指向umi-request@1.3.6 npm包，这里用了ES6种属性的简洁表示法

![image](https://user-images.githubusercontent.com/14038117/119317023-3e436b00-bcaa-11eb-8293-a199d347a8a0.png)

目前的解决办法是回退并指定了 `umi-request` 包版本

**预期**
`umi-request` npm包发布延续之前的规范，发布 ES5 兼容的包，或者使用新的大版本发布ES6代码的包，否则可能使已有的项目构建造成失败。

谢谢你们为开源做出的贡献！

**Comment by hdumok** [comment]
遇到同样的问题，编译出来的代码不支持es5导致页面在IOS9上白屏，费了老大劲定位。版本号规划不合理，这种升级从1.3.5=>1.3.6很不合理。

**Comment by hdumok** [comment]
> 项目中使用到了UglifyJS对代码做压缩，项目构建一直正常，直到最近更新发布了 umi-request@1.3.6，构建失败了
> 
> **我的webpack配置中uglify相关**：
> 
> ```js
> // webpack.config.js
> webpackConfig.plugins.push(
>     new webpack.optimize.UglifyJsPlugin({
>         comments: false,
>         compress: {
>             warnings: false,
>         },
>         except: ['$super', '$', 'exports', 'require'],
>     }),
> );
> ```
> 
> **构建报错**：
> ![image](https://user-images.githubusercontent.com/14038117/119317238-721e9080-bcaa-11eb-936e-d1f39308de34.png)
> 
> 报错指向umi-request@1.3.6 npm包，这里用了ES6种属性的简洁表示法
> 
> ![image](https://user-images.githubusercontent.com/14038117/119317023-3e436b00-bcaa-11eb-8293-a199d347a8a0.png)
> 
> 目前的解决办法是回退并指定了 `umi-request` 包版本
> 
> **预期**
> `umi-request` npm包发布延续之前的规范，发布 ES5 兼容的包，或者使用新的大版本发布ES6代码的包，否则可能使已有的项目构建造成失败。
> 
> 谢谢你们为开源做出的贡献！

可以配置这么解决：
  extraBabelIncludes: [
    "umi-request"
  ]
