### ISSUE TITLE
[Bug] 'prefix' of umi-request is not working as expected

### ISSUE THREAD

**Issue by JackLLLLL** [umijs/umi-request#252]
## What happens?

'prefix' is not working in the latest version, but works in 1.3.5

## Mini Showcase Repository(REQUIRED)

> Please provide a repository using `yarn create @umijs/umi-app` then upload to your GitHub 请提供一个可复现的仓库，使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库

https://github.com/JackLLLLL/umi_report_issue

## How To Reproduce

**Steps to reproduce the behavior:** 1. 2.
see networks

**Expected behavior** 1. 2.
request has prefix '/prefixxxx/', but actually not in version 1.3.9

## Context

- **Umi Version**:
- **Node Version**:
- **Platform**:

**Comment by ttys026** [comment]
works fine by me, need a valid reproduction
https://codesandbox.io/s/charming-frost-2d7s5?file=/src/App.js

**Comment by JackLLLLL** [comment]
> works fine by me, need a valid reproduction
> https://codesandbox.io/s/charming-frost-2d7s5?file=/src/App.js

my apologies. it's one of my chrome plugins that cause this 😢 
But it's strange that only version 1.3.6+ will be effected.

**Comment by JackLLLLL** [comment]
i am closing this issue
