### ISSUE TITLE
不同的实例能够完全独立吗？拦截器互不影响

### ISSUE THREAD

**Issue by GitKou** [umijs/umi-request#264]
🔗 https://github.com/umijs/umi/issues/3019#issuecomment-907026913
我用extend创建了两个实例，但是发现拦截器是互通，请问这个问题现在解决了吗？

**Comment by wzc0x0** [comment]
拦截器传第二个参数`{global:false}`

**Comment by daxiazilong** [comment]
真的是垃圾这个玩意，不同实例的拦截器默认还特么整全局上了  真是考虑的全面

**Comment by GitKou** [comment]
> 拦截器传第二个参数`{global:false}`
