### ISSUE TITLE
请求中设置了responseType: 'blob',无法获取后端的错误提示

### ISSUE THREAD

**Issue by Aqpcet** [umijs/umi-request#289]
如题

**Comment by wavesbig** [comment]
我也是遇到了，感觉让后台改下http状态码吧

**Comment by kokowaa** [comment]
Error对象中的 response.data 是一个Blob对象，只需要将此Blob对象转回Text就可以了。
`
try {
   ...
} catch(e) {
       const filereader = new FileReader();
        filereader.addEventListener('loadend', (e) => {
          const originError= JSON.parse(e.target?.result as string);
          msg.error(originError?.message || '导出失败');
        });
        filereader.readAsText(e.response.data);
}
`
