### ISSUE TITLE
断网下拦截不成功

### ISSUE THREAD

**Issue by khum08** [umijs/umi-request#29]
hello~断网情况下发送请求，使用
![image](https://user-images.githubusercontent.com/32336026/54187567-da796100-44e8-11e9-8b9d-6fce9af30938.png)
![image](https://user-images.githubusercontent.com/32336026/54187586-e49b5f80-44e8-11e9-9a9c-4a7c89173f4a.png)
![image](https://user-images.githubusercontent.com/32336026/54187598-ec5b0400-44e8-11e9-8dfd-056c310089cb.png)
这三种方式拦截，打断点都没走，请问是我的拦截方式不对吗
@sorrycc

**Comment by clock157** [comment]
能否建一个最小的重现 repo @khum08

**Comment by khum08** [comment]
已通过errorHandler拦截到了，谢谢🙏
