### ISSUE TITLE
完善文档：和 fetch 与 axios 的异同

### ISSUE THREAD

**Issue by afc163** [umijs/umi-request#3]
可以在 README 里加一个表格

**Comment by clock157** [comment]
好，现在的文档太丑，我完善一波。

**Comment by afc163** [comment]
你应该用自己写的 library 生成一波，😆

**Comment by clock157** [comment]
好主意，虽然不是组件，但是也可以作为文档建站工具打包一个文档站，部署在 github.io 🤓

**Comment by yutingzhao1991** [comment]
> 虽然不是组件

叫 library 以为着 umi-request 也应该能用才对，不限定在组件上。

**Comment by xiaoxiangmoe** [comment]
@clock157 非展示型的组件的文档（比如 hooks，比如 umi-request， 用 docz 有什么好的展示解决方案吗？）
