### ISSUE TITLE
response 拦截器中不能获取到 response headers

### ISSUE THREAD

**Issue by freezemad** [umijs/umi-request#31]
我用ant-design-pro搭建后台管理系统，使用的是umi-request 是1.0.4，但是发现 每次查询返回的数据是对的  但是response.headers 都是空，而真实返回的头是有的 。 我们的服务器返回的response headers 包括Link , 以及一些自定义的headers 形如X-(...)的header , 但就是在response拦截器中看不到这个数据

**Comment by clock157** [comment]
使用问题: `response.headers.get('X-some-key')`

**Comment by freezemad** [comment]
@clock157  非常感谢
