### ISSUE TITLE
typescript描述文件问题

### ISSUE THREAD

**Issue by bshy522** [umijs/umi-request#33]
https://github.com/umijs/umi-request/blob/3346cd369f8b4685de5099ef01f055d2e9340bef/src/index.d.ts#L65

这一行 handler返回的应该是一个Promise<RequestResponse<T>>吧

**Comment by yesmeck** [comment]
你是实际碰到了问题？还是只是心里有疑问

**Comment by bshy522** [comment]
> 你是实际碰到了问题？还是只是心里有疑问？

实际遇到问题

**Comment by yesmeck** [comment]
直接说碰到的问题

**Comment by bshy522** [comment]
> 直接说碰到的问题

就是ts里面 会报错啊，说这个地方不能收这个类型  我也是刚开始用ts，从错误看结合这个描述文件看，应该是这里 handler函数的返回定义的不对。代码里面是支持返回一个promise的

**Comment by bshy522** [comment]
https://github.com/umijs/umi-request/blob/b7ddc5f95d9b2ab5c752abe7531566b7dd4de632/src/lib/fetch.js#L24

**Comment by yesmeck** [comment]
handler 现在不支持返回 promise。

#28

**Comment by bshy522** [comment]
> handler 现在不支持返回 promise。
> 
> #28

额。。我看上面那个逻辑是支持的吧。。

**Comment by yesmeck** [comment]
那是还没合并的代码。

**Comment by bshy522** [comment]
> 那是还没合并的代码。

好的，多谢。

期待发新版

**Comment by clock157** [comment]
@bshy522 那个 mr 有问题一直没合，你能说下你的具体场景和需求吗？有兴趣重新提 mr 吗。

**Comment by eightHundreds** [comment]
文档中的代码段
```
/**
* 5. For the status code is actually 200 errors
*/
request.interceptors.response.use(async (response) => {
  const data = await response.clone().json();
  if(data && data.NOT_LOGIN) {
    location.href = 'login url';
  }
  return response;
})

```

在ts不支持,拦截方法返回的是Promise
