### ISSUE TITLE
有没有办法在拦截器里直接返回response.data

### ISSUE THREAD

**Issue by liujians** [umijs/umi-request#35]
因为服务端的接口返回是{ code:0,message:"string",data:{}}
我们在拦截器中根据code和message进行处理错误
然后业务中只需要取data就行了，
拦截器中我试了一下，返回response以外的都会undefined
目前在model层面是每一个response都取response.data的，不知道是否有什么好的办法

**Comment by clock157** [comment]
拦截器中的 response 需要处理一下才能使用。

`respone.clone().json()`

**Comment by liujians** [comment]
我描述的有问题，我直接return response.clone().json()，在model层拿到的是undefined，
也就是说拦截器中只能返回response这一点是我想改变的 @clock157

**Comment by Thyiad** [comment]
@liujians 解决没

**Comment by liujians** [comment]
@Thyiad 没有解决。还是先用axios了。不然每次在model层都需要多取一下data

**Comment by Thyiad** [comment]
@liujians 同感。明天我再来试试直接改response

**Comment by Thyiad** [comment]
@liujians 对了，忘记说了。我最后发现只要包一层就好了，就是调用的时候，使用你封装的那个函数：
![image](https://user-images.githubusercontent.com/3324812/55929093-c17de000-5c4d-11e9-94ac-c5cb6502d68d.png)

**Comment by liujians** [comment]
@ Thyiad 是可以自己封装一个req方法来解决这个问题。谢谢了。之前的代码都是用umi block命令生成的区块，所以内置的service代码都是直接调的request，懒得一个一个改，想的是如果改拦截器里的返回就解决这个问题了。看来还是只能一个一个改之前的request调用了

**Comment by clock157** [comment]
response 的拦截器必须要返回一个 Response，所以不能直接返回 response.clone().json()，这个问题不需要修改拦截器。只需要如 @Thyiad 所说，再封装一层即可。

**Comment by MinJieLiu** [comment]
@liujians 

```js
request.use(async (ctx, next) => {
  await next();

  const { res } = ctx;
  const { success = false } = res; // 假设返回结果为 : { success: false, errorCode: 'B001' }
  if (!success) {
    // 对异常情况做对应处理
  }
})
```

这个可以？
