### ISSUE TITLE
cancellation support?

### ISSUE THREAD

**Issue by leftstick** [umijs/umi-request#36]
nice lib, 不过目前没看到有关于cancellation的内容，有考虑支持么？谢谢

**Comment by clock157** [comment]
你好，能说下具体使用场景吗

**Comment by xiaohuoni** [comment]
updata cancell？

**Comment by leftstick** [comment]
效果类似[axios-cancellation](https://github.com/axios/axios#cancellation)，我期待的效果是能把发出但还没返回的请求中断掉。

当然这种操作不是必须的，可以通过其他手段弥补。只是好奇，有没有支持计划。

谢谢

**Comment by clock157** [comment]
如果再次收到类似的需求，会支持。

**Comment by leftstick** [comment]
我暂时先关闭吧，严格意义上我这个都不算是feature request
