### ISSUE TITLE
请求拦截器中回调使用异步操作无法修改options的值

### ISSUE THREAD

**Issue by mabelyong** [umijs/umi-request#39]
调用请求拦截器`request.interceptors.request.use`方法，在拦截器中为每个请求`header`添加`token`，因为`localforage`读取`token`是异步操作，将读取到的值设置到`header`中不会成功。

见代码：
```javascript
// request拦截器
request.interceptors.request.use(async (url, options) => {
  options.headers.Authorization = '123';
  const token = await '456';  // 模拟localforage.getItem('token')异步操作
  options.headers.Authorization = token;

  console.log(options.headers.Authorization);  
  //  这里打印出来的Authorization值是正确的'456'，
  //  真实请求中的Authorization值仍然还是'123'
  //  相同的操作换成axios没有问题
  return {url, options};
});
```

**Comment by yesmeck** [comment]
https://github.com/umijs/umi-request/pull/28

**Comment by clock157** [comment]
添加 header 不需要在 interceptors 里做，在请求时传入 { headers: {Authorization: 'token'} } 就可以的

**Comment by qingfengmy** [comment]
现在已经是好使的了

**Comment by paradox010** [comment]
依然不支持。如果token变化了怎么办。那就得在request外面再包一层？。。。。。

**Comment by paradox010** [comment]
抱歉，现在是ok的了。写错了字段

**Comment by dobeweb** [comment]
eslint 有报错
(parameter) url: string
类型“(url: string, options: RequestOptionsInit) => Promise<{ url: string; options: { charset?: "utf8" | "gbk" | undefined; requestType?: "json" | "form" | undefined; data: any; params?: object | URLSearchParams | undefined; ... 26 more ...; window?: any; }; }>”的参数不能赋给类型“RequestInterceptor”的参数。
  类型“Promise<{ url: string; options: { charset?: "utf8" | "gbk" | undefined; requestType?: "json" | "form" | undefined; data: any; params?: object | URLSearchParams | undefined; paramsSerializer?: ((params: object) => string) | undefined; ... 25 more ...; window?: any; }; }>”与类型“{ url?: string | undefined; options?: RequestOptionsInit | undefined; }”不具有相同的属性。ts(2345)

**Comment by ShawLyon** [comment]
request.interceptors.request.use((url, options) => {
  const token = `JWT ${sessionStorage.getItem('token')}`;
  return {
    url,
    options: {
      ...options,
      headers: {
        Authorization: token,
      },
      interceptors: true,
    },
  };
});
TS

**Comment by ShawLyon** [comment]
`request.interceptors.request.use((url, options) => {
  const token = `JWT ${sessionStorage.getItem('token')}`;
  return {
    url,
    options: {
      ...options,
      headers: {
        Authorization: token,
      },
      interceptors: true,
    },
  };
});`

**Comment by ShawLyon** [comment]
`
request.interceptors.request.use((url, options) => {
  const token = `JWT ${sessionStorage.getItem('token')}`;
  return {
    url,
    options: {
      ...options,
      headers: {
        Authorization: token,
      },
      interceptors: true,
    },
  };
});
`

**Comment by ShawLyon** [comment]
ts
```
request.interceptors.request.use((url, options) => {
   const token = ‘token’;
   return {
    url,
    options: {
      ...options,
      headers: {
        Authorization: token,
      },
      interceptors: true,
    },
  };
});
```
