### ISSUE TITLE
使用了query-string导致无法兼容ie9，建议能否向下兼容呢

### ISSUE THREAD

**Issue by Symboler** [umijs/umi-request#40]

**Comment by sorrycc** [comment]
基于 umi 的话，query-string 已默认加入编译的，遇到的问题是啥？

**Comment by Symboler** [comment]
> 基于 umi 的话，query-string 已[默认加入编译](https://github.com/umijs/es5-imcompatible-versions/blob/master/package.json#L42)的，遇到的问题是啥？

嗯嗯，昨天碰到了没有被编译的情况，导致打出的umi.js里面有箭头函数，今天重新安装包没有复现出来，我自己再看看是哪里的问题，谢谢回复！
