### ISSUE TITLE
errorHandler 的error中没有request请求的参数？

### ISSUE THREAD

**Issue by liuxiawang** [umijs/umi-request#46]
想在token过期时无感知的刷新token并继续执行原有的操作，在errorHandler中捕获到401错误，刷新token成功后，再次调用原先请求，但是没有post请求body里面的参数，请问这个有什么更好解决办法嘛？如果使用response拦截器的话，重新请求了接口还是会再走一遍errorHandler函数，在yield call()中得不到正确的返回结果...

**Comment by clock157** [comment]
post 的 body 没有带在 response 中，如果本次请求失败，可以在服务端将你需要的额外参数写在返回的 header 中，供你重试时使用。

**Comment by clock157** [comment]
```js
const { response } = error;
const failedBody = response.headers.get('failedBody');
```
