### ISSUE TITLE
在umi1.0里使用，build失败

### ISSUE THREAD

**Issue by ergoulee** [umijs/umi-request#48]
npm start都没问题，但是build失败，报错如下
![屏幕快照 2019-04-29 下午4 43 15](https://user-images.githubusercontent.com/15899945/56885051-16b74f80-6a9e-11e9-88a8-2443876dedee.png)
![屏幕快照 2019-04-29 下午4 45 43](https://user-images.githubusercontent.com/15899945/56885145-4bc3a200-6a9e-11e9-81dc-3eff85eff618.png)

package.json如下
![屏幕快照 2019-04-29 下午4 47 15](https://user-images.githubusercontent.com/15899945/56885229-83324e80-6a9e-11e9-813d-0602c014a3e9.png)

**Comment by clock157** [comment]
可以升级 umi 2.x 么? 这个箭头函数的包看起来不是 umi-request 的

**Comment by clock157** [comment]
有问题再反馈，先关闭
