### ISSUE TITLE
关于useCache: true, ttl: 10000一些疑问

### ISSUE THREAD

**Issue by cooliean** [umijs/umi-request#50]
// 使用缓存, 只有get时有效. 单位毫秒, 不加ttl默认60s, ttl=0不过期. cache key为url+params组合
request('/api/v1/some/api', { params: { hello: 'world' }, useCache: true, ttl: 10000 });

这个使用后，试缓存再那里的呢？浏览器的localStorage我没有看到，谢谢：）

**Comment by clock157** [comment]
通过 Map 实现缓存在内存中，你遇到什么问题了吗？
返回的 response 不能放在 localStorage

**Comment by cooliean** [comment]
没有，了解一下，谢谢

**Comment by cooliean** [comment]
如果我想强制更新怎么做好呢

**Comment by clock157** [comment]
你可以在请求接口时使用 useCache: false 不使用缓存，或者刷新当前页面。目前没有接口主动清空缓存

**Comment by xizheng** [comment]
看注释里还有localcache 和 sessioncache，能否使用呢？
