### ISSUE TITLE
response 返回值response 没有文档中的 data 选项, 只有 ReadableStream

### ISSUE THREAD

**Issue by kelefun** [umijs/umi-request#77]
背景umi-request version  1.2.11  ,  chrome 78.0.3904.108  
请求方式  
```js
import { extend } from 'umi-request';
// errorHandler 拷贝的 ant-design-pro
const request = extend({
  errorHandler, 
  credentials: 'include', 
});

const response = request('/proxy/login', {
    method: 'POST',
    data: params,
  })

```
返回结果如下
![{FB83A5BB-9D7D-4A2D-8CF6-078FFEA2D641}_20191126151315](https://user-images.githubusercontent.com/20576242/69607782-fade5100-1060-11ea-9112-9f7c701c779b.jpg)

问题 怎么方便的获取后台服务返回的文本?

**Comment by leftstick** [comment]
你的`response`是怎么打印出来的？

**Comment by kelefun** [comment]
> 你的`response`是怎么打印出来的？

截图是代码里的 console.log(reponse) 打印出来的
```js
//dva somecode 
 effects: {
    *signin({ payload }, { call, put }) {
      const response = yield call(login, payload);
      console.log(response)
```
-- 
目前看来应该跟返回状态码有点关系   
刚刚测试了下如果返回状态码=200 打印出来的就是后台返回的值,

**Comment by chenjsh36** [comment]
umi-request 默认对状态码为 200 的请求自动根据响应类型做序列化处理和解析，返回后台对应的值，如果状态码非 200，则会走 errorHandler ，用户可以在 errorHandler 里对响应做对应的处理，详情可参考[文档](https://github.com/umijs/umi-request/blob/master/README_zh-CN.md#%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86)，如果不需要自动处理可通过 **parseResponse** 关闭处理简化，并通过**中间件**自定义响应处理方式。

**Comment by artemdumanov** [comment]
To be honest I was so irritated with umi library experience since it's impossible to find an answer to your question or if there is an answer in Chinese. I am strongly convinced that umi community should be using English more extensively as the word does.

After 3 hours I've managed the issue. Here is the concrete recipe.

```
export const errorHandler = error => {
    const { response, data } = error;

    response.data = data
    return response
}
```
