### ISSUE TITLE
response interceptor;response.headers.append undefined

### ISSUE THREAD

**Issue by GitYmf** [umijs/umi-request#78]
参照案例response interceptor；使用response.headers.append时错误提示read property 'headers' of undefined

**Comment by kzabc** [comment]
request.interceptors.response.use((response) => {
  console.log(response);
   console.log(response.headers.get('authorization'));
  return response;
});

解决了吗？ 我也获取不到headers

**Comment by chenjsh36** [comment]
> 参照案例response interceptor；使用response.headers.append时错误提示read property 'headers' of undefined

提示 read property 'headers' of undefined 应该是 response 没有返回，麻烦提供下 demo 仓库，正常是可以获取到的，但是存在部分浏览器处于保护策略禁止对 response header 做修改的情况

**Comment by webxiaobian** [comment]
I followed the documentation to get response.headers, but an empty object was returned

**Comment by webxiaobian** [comment]
> I followed the documentation to get response.headers, but an empty object was returned

Then I used axios and it works fine

**Comment by ruizhang-chowbus** [comment]
I encountered the same problem

**Comment by ruizhang-chowbus** [comment]
![image](https://user-images.githubusercontent.com/62980775/83827446-faf69200-a710-11ea-8247-d5485632cd97.png)

**Comment by YuGe** [comment]
@chenjsh36 Could you reopen it? I've the same issue.
