### ISSUE TITLE
headers 请求头设置问题

### ISSUE THREAD

**Issue by RSH-KAVEN** [umijs/umi-request#79]
requestType: "json",
headers: {
    accept: "application/json",
    content-type: "application/json"
}
请求头内容如上，
发起请求时，实际得到的请求头为
Accept: application/json; ，application/json
Content-Type: application/json;UTF-8 , application/json
手动设置的与默认的自动拼接到一起，中间还有个逗号
只有当accept 和 content-type 大小写完全一致时才不会出现该错误

**Comment by chenjsh36** [comment]
'requestType' 当 data 为对象或者数组时， umi-request 会根据 requestType 动态添加 headers 和设置 body（可传入 headers 覆盖 Accept 和 Content-Type 头部属性）:
1. requestType === 'json' 时, (默认为 json )
options.headers = {
  Accept: 'application/json',
   'Content-Type': 'application/json;charset=UTF-8',
    ...options.headers,
 }

所以用户无需自己再手动添加，如果想覆盖 headers 保持大小写一致就行了的

**Comment by tuqiyu** [comment]
如果我想全局增加请求头，有相关的设置吗
