### ISSUE TITLE
有没有合适的办法来修改response的data

### ISSUE THREAD

**Issue by CoolBerry** [umijs/umi-request#85]
想要实现统一修改server返回数据的格式，例如首字母都改成小写。

拦截器似乎无法修改到data，有没有合适的办法来实现这个功能呢？

谢谢。

**Comment by MinJieLiu** [comment]
@CoolBerry 
试试
```js
request.use(async (ctx, next) => {
  await next();

  const { res } = ctx;
  const { success = false } = res; // 假设返回结果为 : { success: false, errorCode: 'B001' }
  if (!success) {
    // 对异常情况做对应处理
  }
})
```

**Comment by starhu521** [comment]
> @CoolBerry
> 试试
> 
> ```js
> request.use(async (ctx, next) => {
>   await next();
> 
>   const { res } = ctx;
>   const { success = false } = res; // 假设返回结果为 : { success: false, errorCode: 'B001' }
>   if (!success) {
>     // 对异常情况做对应处理
>   }
> })
> ```

如果需要在判断success之后，把数据整理之后（处理之后结果res为any，没有success字段了）返回出去，怎么操作呢？
