### ISSUE TITLE
如何处理 net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by gaoobin** [umijs/umi-request#86]
服务端停了前端会请求出错 （net::ERR_CONNECTION_REFUSED）
但是没法处理，errorHandler里的error信息就一个字符串（TypeError: Failed to fetch）
还想通过url判断下结果获取不到，没有options信息。
是我用的不对还是errorHandler就这么简单

**Comment by gaoobin** [comment]
umi-request的坑多，用别的工具也没遇到过这么多问题，浪费了好多时间

**Comment by chenjsh36** [comment]
net::ERR_CONNECTION_REFUSED 属于网络故障或者请求被阻止中的一种，这种情况下原始 fetch 请求会直接 reject 并抛出 error 信息，而不会像 400、500 进入 fetch.then 后被 umi-request 先处理后再返回给用户在 errorHandler 中处理，所以 error 中少了相关的 request、response 信息，后续会更新对这种情况下的异常支持情况。关于 fetch 更多信息详见[mdn 文档](https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch)

**Comment by gaoobin** [comment]
期待改进

**Comment by zemelLeong** [comment]
改进了吗

**Comment by zemelLeong** [comment]
项目废弃了？
