### ISSUE TITLE
封装的太差，建议将现在的umi-request从umijs中移除

### ISSUE THREAD

**Issue by gaoobin** [umijs/umi-request#87]
简单的事情搞这么复杂，一不小心就踩一个坑，一个umi-request这几天踩了无数坑。浪费了太多时间，用的我开始怀疑人生，感觉jquery时代比这都强百倍。客观评价，不吹不黑

**Comment by chenjsh36** [comment]
* 如果在使用中遇到什么坑，欢迎提交 issue ，也欢迎参与提交 pr 参与共建；
* umi-request 虽然作为 umi 内置的请求库，但并不强制使用，你也可以引入其他请求库进行开发；

**Comment by gaoobin** [comment]
既然作为内置的，使用umi肯定都会优先考虑这个。但是采坑的成本真的很高，等我有空了整理一下踩过的坑

**Comment by chj-damon** [comment]
@gaoobin 坑呢？

**Comment by gaoobin** [comment]
@chj-damon 你觉得这个插件好是吧？抱歉我早就弃用这个了，所以也不想在上面花时间整理
