### ISSUE TITLE
中间件获取响应头

### ISSUE THREAD

**Issue by snowtreetree** [umijs/umi-request#91]
使用中间件处理请求，返回的接口如下，在其他issue里面有说通过[headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers#Methods)，能过拿到响应头。但是好像没找见。
![image](https://user-images.githubusercontent.com/30932683/71072331-3c25d480-21b9-11ea-8f36-22721a737f8f.png)

**Comment by snowtreetree** [comment]
已找到getResponse

**Comment by Lydiayaya** [comment]
你好，请问你是怎么找到的啊
