### ISSUE TITLE
为什么取消请求是基于已经撤销的方案？

### ISSUE THREAD

**Issue by shx996** [umijs/umi-request#92]
假取消优点是什么？axios和fetch都可以做到终止请求的，所以我不理解为什么要用已经撤销了的方案？

**Comment by imrickywong** [comment]
是的，正确的用法不是用`AbortController`么.

不过`AbortController`支持度还有点问题

**Comment by chenjsh36** [comment]
> 假取消优点是什么？axios和fetch都可以做到终止请求的，所以我不理解为什么要用已经撤销了的方案？

axios和fetch都可以做到终止请求吗？说对了一半， axios 是基于 XMLHttpRequest，而 XMLHttpRequest 提供 abort API，而原生 fetch 并不提供取消请求的能力，而取消请求在请求场景属于比较通用的能力，所以我们实现了一个伪取消请求能力。

为什么用一个已经撤销的方案？取消请求的设计是基于 proposal-cancelable-promises 这个方案上去实现，虽然方案被撤销了，但其设计有其合理和规范。

为什么不用 AbortController ？因为目前还处于实验阶段，暂时无法在生产环境下使用。
