### ISSUE TITLE
如何下载application/octet-stream文件？

### ISSUE THREAD

**Issue by guxing1992** [umijs/umi-request#99]
当我使用原生fetch下载文件的时候是成功的，但是换成umi-request就报
20:1 Uncaught (in promise) SyntaxError: Unexpected token @ in JSON at position 0
错误。
```js
  import request from 'umi-request';
   const reqUrl = `${SERVER_PRX}/contractTaskAttachment/downLoad/${attachmentId}`;
    const AUTHTOKEN = localStorage.getItem('auth_token') || '';
    request(reqUrl, {
      responseType: 'blob',
      headers: {
        Authorization: `Bearer ${AUTHTOKEN}`,
      },
    })
      .then(res => res.blob())
      .then(res => {
        const content = res;
        const blob = new Blob([content]);
        if ('download' in document.createElement('a')) {
          // 非IE下载
          const elink = document.createElement('a');
          elink.download = fileName;
          elink.style.display = 'none';
          elink.href = URL.createObjectURL(blob);
          document.body.appendChild(elink);
          elink.click();
          URL.revokeObjectURL(elink.href); // 释放URL 对象
          document.body.removeChild(elink);
        } else {
          // IE10+下载
          navigator.msSaveBlob(blob, fileName);
        }
      });
```
将request换成fetch就成功了。

**Comment by wangym0203** [comment]
同问 遇到相同问题 SyntaxError: Unexpected token % in JSON at position 0

**Comment by wangym0203** [comment]
<img width="451" alt="企业微信截图_20200114162012" src="https://user-images.githubusercontent.com/26135370/72326447-3228c000-36ea-11ea-8c8d-279bb64697da.png">
使用了try catch 暂时跳过了这个问题，求解

**Comment by chenjsh36** [comment]
尝试传入参数：parseResponse: false 看看能否解决

``` javascript
  import request from 'umi-request';
   const reqUrl = `${SERVER_PRX}/contractTaskAttachment/downLoad/${attachmentId}`;
    const AUTHTOKEN = localStorage.getItem('auth_token') || '';
    request(reqUrl, {
      responseType: 'blob',
      headers: {
        Authorization: `Bearer ${AUTHTOKEN}`,
      },
      parseResponse: false, // 添加参数
    })
      .then(res => res.blob())
      .then(res => {
        const content = res;
        const blob = new Blob([content]);
        if ('download' in document.createElement('a')) {
          // 非IE下载
          const elink = document.createElement('a');
          elink.download = fileName;
          elink.style.display = 'none';
          elink.href = URL.createObjectURL(blob);
          document.body.appendChild(elink);
          elink.click();
          URL.revokeObjectURL(elink.href); // 释放URL 对象
          document.body.removeChild(elink);
        } else {
          // IE10+下载
          navigator.msSaveBlob(blob, fileName);
        }
      });
```

**Comment by guxing1992** [comment]
还是报3:1 Uncaught (in promise) SyntaxError: Unexpected token P in JSON at position 0

**Comment by liangxp** [comment]
@guxing1992 只能fetch？这是啥道理哦，不是都是基于fetch封装的么？

**Comment by guxing1992** [comment]
不懂，就把request改为fetch就OK了

**Comment by skystardust** [comment]
这里是由于使用了response.clone().json() 产生了错误，可以针对blob类型的响应跳过
![image](https://user-images.githubusercontent.com/47660938/87390999-813da800-c5dc-11ea-8de5-7fbc769b1fee.png)

**Comment by Plortinus** [comment]
不reopen一下？

**Comment by BearD01001** [comment]
遇到了同样的问题，有比较优雅的解决方案吗

**Comment by bigbigbo** [comment]
我调试源码根本不会报这个错，但是使用编译后的代码就是会报这个错

**Comment by bigbigbo** [comment]
一样的问题，换 fetch 就行，调试源码也没有报错

**Comment by hemengke1997** [comment]
> 这里是由于使用了response.clone().json() 产生了错误，可以针对blob类型的响应跳过
> ![image](https://user-images.githubusercontent.com/47660938/87390999-813da800-c5dc-11ea-8de5-7fbc769b1fee.png)

直接从`umi-request` 中引入`request`， 不做任何的拦截器处理，一样报这个错

**Comment by phucuongit** [comment]
I got res.blob() not a function
How I solve it?

**Comment by baobeidaodao** [comment]
responseType: 'blob',
parseResponse: false

**Comment by lynxerzhang** [comment]
我也遇到了类似问题，fetch确实可以

**Comment by Miever1** [comment]
没人解释一下吗？😂

**Comment by cuijiudai** [comment]
responseType: 'blob',
parseResponse: false

加上和原来没有区别

**Comment by Miever1** [comment]
> 加上和原来没有区别

直接换fetch吧

**Comment by zhangwenboi** [comment]
![image](https://github.com/umijs/umi-request/assets/86345608/0c03341d-ef0d-475c-b198-89b947756a84)

    //拦截之后按照fetch的来之后就行了
` const res = await request<any>('/api/file/download/', {
        responseType: 'blob',
        parseResponse: false,
        method: "POST",
    })
    const data = await res.blob()
`
